### ISSUE TITLE
Interestring repositories!

### ISSUE THREAD

**Issue by alex5250** [stravnik/toxic-repos#19]
It is not the real project ,but there are quite straightforward political messages. I think can be added to other list called : Messages !

https://github.com/LinghaoChan/StandwithRussian
https://github.com/Py-debug/StandwithRussian
https://github.com/PutinMyLeader/PutinMyLeaderTEST.github.io
https://github.com/YuryMoskaltsov/

**Comment by open-source-peace** [comment]
Данный issue - это толстый троллинг от токсичного автора.

**Comment by alex5250** [comment]
https://github.com/AntonyHanna/Blyatmir-Putin-Bot
https://github.com/rusty323/Me-love-Putin


I really like it : https://github.com/putinapproved/putinapproved
https://github.com/independent-opinion/putin.live

**Comment by stravnik** [comment]
@alex5250 ты забанен за тупой спам.
