### ISSUE TITLE
xlsx format

### ISSUE THREAD

**Issue by mrbinwin** [stravnik/toxic-repos#2]
Hi! Thank you for your lists.
It's helpful project, but why did you decide to use xlsx format of the files? Many people are scared to download and open such kind of file types. Wouldn't it be better to use just markdown tables?

**Comment by stravnik** [comment]
Hello. In addition to xlsx, the repository has lists in txt and json format. And thanks for your comment, I'll add markdown tables a little bit later.

**Comment by nemirlev** [comment]
@stravnik A u accept merge request? I can help with this.

**Comment by stravnik** [comment]
@nemirlev Of course, I will be very grateful for the help!

**Comment by lemenkov** [comment]
> Hi! Thank you for your lists. It's helpful project, but why did you decide to use xlsx format of the files? Many people are scared to download and open such kind of file types. Wouldn't it be better to use just markdown tables?

Agree with @mrbinwin. I believe there should be makefile which generates TXT-files (or XLS if anyone really wants it) from available JSON-files.

**Comment by stravnik** [comment]
done

**Comment by k-popov** [comment]
The repo currently has the file in TSV format that is easily parsed with tools like LibreOffice Calc or MS Excel.
