### ISSUE TITLE
Ошибка при добавлении в список

### ISSUE THREAD

**Issue by zloirock** [stravnik/toxic-repos#24]
![image](https://user-images.githubusercontent.com/2213682/160602288-3396d5bf-3350-4a76-93b6-871185742bd6.png)

Пожалуйста, ссылочку на агитацию и призыв в студию.

**Comment by stravnik** [comment]
Спасибо за уточнение. Так получилось из-за того, что репа изначально основывалась на этом списке: https://docs.google.com/spreadsheets/d/1H3xPB4PgWeFcHjZ7NOPtrcya_Ua4jUolWm-7z9-jSpQ/htmlview?pru=AAABf8BQoqs*H6L7gipADBaYcl_ITqoK7g#
Ваш репозиторий будет удален из списка.

**Comment by LEv145** [comment]
Я не организатор, но могу сказать, что БД, которая сейчас кривая, надеюсь разработаем лучше, возможно это ложная притензия
Я за то, чтобы в БД добавлялись ссылки на коммиты с подробным описанием, которые могут являться доказательствами
