### ISSUE TITLE
HTTPToolkit

### ISSUE THREAD

**Issue by vikarti** [stravnik/toxic-repos#25]
https://httptoolkit.tech/
(исходники - https://github.com/httptoolkit, заявлено 100% opensource)
При заходе без VPN - баннер политического плана.
Предложение оформить подписку до сих про висит и цены старые в рублях. Старые подписки не отменяли. Агрессивности в общении не замечено.

**Comment by stravnik** [comment]
> https://httptoolkit.tech/ (исходники - https://github.com/httptoolkit, заявлено 100% opensource) При заходе без VPN - баннер политического плана. Предложение оформить подписку до сих про висит и цены старые в рублях. Старые подписки не отменяли. Агрессивности в общении не замечено.

Сейчас не наблюдаю проблем при заходе с ip РФ
