### ISSUE TITLE
Кодировка на ру

### ISSUE THREAD

**Issue by daitonaaa** [stravnik/toxic-repos#28]
Привет! Спасибо вам за репозиторий
не так давно заметили проблемы с кодировкой
<img width="946" alt="image" src="https://user-images.githubusercontent.com/24705476/162209556-a49ccb9b-b5cd-4387-ad41-58d27c46c706.png">

**Comment by stravnik** [comment]
Привет.
Спасибо, мы в курсе проблемы.
Сегодня постараюсь к вечеру поправить данную проблему.

**Comment by stravnik** [comment]
Исправили.
https://github.com/stravnik/toxic-repos/commit/14934fd1bfac8c2e98f7ddd6e06aa4d3e7c37a2b

**Comment by daitonaaa** [comment]
@stravnik cпасибо!
