### ISSUE TITLE
Add relevant info to the README

### ISSUE THREAD

**Issue by grongor** [stravnik/toxic-repos#34]
[![Stand With Ukraine](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/banner2-direct.svg)](https://stand-with-ukraine.pp.ua)

You should add this info to the README and the website itself so that the people know the truth and not just the propaganda.

 See proposed changes: https://github.com/stravnik/toxic-repos/pull/33

**Comment by stravnik** [comment]
Nope.

**Comment by MaxGraey** [comment]
Why not? Do you support the war (or "special operation")? Or do you hide the truth? Maybe you are part of the propaganda and this repository is part of the information war? Then you are an active participant and accomplice, not a neutral player. You are already making weapons out of OSS, contributing "hit list", most members of which only express support for Ukraine and are directed against the war.

**Comment by stravnik** [comment]
We are about "soft", not about politics.

**Comment by webknjaz** [comment]
> not about politics.

🤡🤡🤡

This is a typical line of the russian nazi propaganda.

I guess now everyone can see what you're really doing here 🤷‍♂️

**Comment by ctrlok** [comment]
You should add info from your profile to this repo as well, lol 

![CleanShot 2022-04-13 at 21 18 51@2x](https://user-images.githubusercontent.com/3265316/163244904-2fdcf77b-368f-4096-aa1d-63b711139b8a.png)

**Comment by mykola-drone-dev** [comment]
Typical ruscist 🐖🐕

**Comment by stravnik** [comment]
Мы не будем добавлять никаких баннеров.
Мы стараемся держаться вне политики.
Если вам есть что предложить для списка, то добро пожаловать.
Мы будем добавлять информацию о всех токсичных репозиториях, независимо от национальности и места проживания их создателей. Да, даже русских разработчиков. Но проблема в том, что в список не поступило ни одного предложения о таких репозиториях.

**Comment by stravnik** [comment]
Do you want dialogue? Follow the link.
[https://github.com/stravnik/toxic-repos/discussions/35](https://github.com/stravnik/toxic-repos/discussions/35)

**Comment by ctrlok** [comment]
> Но проблема в том, что в список не поступило ни одного предложения о таких репозиториях. 

легко https://github.com/stravnik/toxic-repos/compare/main...ctrlok:patch-1

**Comment by stravnik** [comment]
> легко #36

Вы верите всему что написано в интернете?

**Comment by ctrlok** [comment]
@stravnik ну как верю, у меня уже экс колегу с которой я вместе работал в Datarbot убили когда она волонтерила и крёстный погиб. Да и зачем верить всему что в интернете, если можно посмотреть за окно?

**Comment by yermulnik** [comment]
> If you have something to suggest for the list, then welcome.
> We will add information about all toxic repositories, regardless of the nationality and place of residence of their creators.

Looking at #36 the words I quoted above are just about nothing 🤷🏻

**Comment by stravnik** [comment]
@ctrlok да когда же вы поймете что не мы(простые жители РФ) вас убиваем? И предвкушая вопросы и призывы о митингах и т.д. Нет, я не буду выходить на протесты и прочее, я не хочу из-за этого присесть в тюрьму.

**Comment by ctrlok** [comment]
@stravnik ты споришь с обвинениями которые я тебе не выдвигал. Так и я могу сказать что ты меня утюгом назвал и спросить с этим. Смысл?
