### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by hannesvdvreken** [stravnik/toxic-repos#50]
Stop using bootstrap then because it is “toxic”.

https://twitter.com/getbootstrap/status/1514318094566518788?s=21&t=eF6npSjn1uN3mZOgAh2cTQ

**Comment by EvilLord666** [comment]
We don't need bootstrap anymore as a lightweight substitution we could use pure (https://github.com/pure-css/pure) or use native solution - flexbox
