### ISSUE TITLE
Добавить в список AssemblyScript

### ISSUE THREAD

**Issue by EvilLord666** [stravnik/toxic-repos#52]
Этот репозиторий https://github.com/AssemblyScript/assemblyscript как минимум содержит политический лозунг.

**Comment by MaxGraey** [comment]
Еще как поддерживает, я его core контрибутор. Вы сами себя изолируете от технологий! Прошу, продолжайте в том же духе!

**Comment by stravnik** [comment]
@MaxGraey Вы даже не понимаете сути этого списка. Впрочем не удивительно.

**Comment by MaxGraey** [comment]
@[stravnik](https://github.com/stravnik) Как раз очень даже хорошо понимаю. Где репозитарии, которые поддерживали и поддерживают BLM? Их нету! Где репозитарии которые поддерживают войну в украине и выставляют георгиевские ленточки Z и V? Их нету! Зато есть репозитарии которые поддерживают Украину. Поэтому не надо из себя строить борца за чистоту софта. Попахивает нацизмом

**Comment by MaxGraey** [comment]
Вот кстати список компаний которые поддерживают BLM в 2022:
https://builtin.com/diversity-inclusion/companies-that-support-black-lives-matter-social-justice

Почему их OSS проекты не в вашем списке?

    A16z
    Bumble
    Cisco
    DocuSign
    DoorDash
    Eaze
    Etsy
    Grindr
    Grubhub
    IBM
    Matchstick Ventures
    Microsoft
    Niantic
    Peloton
    Reddit
    Shopify
    Snap
    Uber
    Techtonic
    Comcast
    Slack
    SoftBank
    PayPal

**Comment by EvilLord666** [comment]
@MaxGraey, переживем без ваших политизированных технологий и токсичных репо и построим свои, которые не будут дискриминировать людей по территориальному и национальному признаку.

**Comment by MaxGraey** [comment]
Еще раз ответьте, пожалуйста, где репозитории поддерживающие политические лозунги BLM?

**Comment by stravnik** [comment]
@MaxGraey Вот честно, большое спасибо за список выше, обязательно обработаю его и обновлю репу в течении пары дней.
А отсутствие того о чем вы написали объясняется просто: никто не репортил их. Этот список составляется исключительно из репортов пользователей.

**Comment by AlexZas18** [comment]
Человек задал отличный вопрос:
@[stravnik](https://github.com/stravnik) Как раз очень даже хорошо понимаю. Где репозитарии, которые поддерживали и поддерживают BLM? Их нету! Где репозитарии которые поддерживают войну в украине и выставляют георгиевские ленточки Z и V (в контексте поддержки войны)? Их нету! Зато есть ИСКЛЮЧИТЕЛЬНО репозитарии которые поддерживают Украину. Поэтому не надо из себя строить борца за чистоту софта. Попахивает нацизмом

На что получает ответ : 

@MaxGraey Вот честно, большое спасибо за список выше, обязательно обработаю его и обновлю репу в течении пары дней.
А отсутствие того о чем вы написали объясняется просто: никто не репортил их. Этот список составляется исключительно из репортов пользователей.


Дополню тем что смог найти:

Очень интересные ребята: https://github.com/OpenSourcePolitics

Но это просто репозитории которые по првде говоря являются politics-driven
https://github.com/yegor256/sozidanie.github.io
https://github.com/trumptax/trumptax.me
https://github.com/TrumpForUSA/HowTrumpWins2020
https://teamavo.github.io/BlackLivesMatter/
https://github.com/TeamAvo/BlackLivesMatter



StandWithRussia можно ввести конечно категорию сообщения, но это бесполезно таких реп вагон и маленькая тележка:
https://github.com/LinghaoChan/StandwithRussian
https://github.com/Py-debug/StandwithRussian (кстати веселый персонаж)
