### ISSUE TITLE
purpose?

### ISSUE THREAD

**Issue by DrGo** [stravnik/toxic-repos#55]
what is the point of making a listing of all repos that express an opinion that you do not agree with?

**Comment by 3m4r5** [comment]
to avoid using as much malware as possible

**Comment by k-popov** [comment]
What's the point in creating an issue for the project you don't understand the purpose of?

**Comment by kgnfth** [comment]
> what is the point of making a listing of all repos that express an opinion that you do not agree with?

Why would anyone support american propaganda like saying Russia is doing genocide while
Just because america said it, the whole europe is following america
while america invaded and keeps invading non white peoples countries !!!!!!!
does that makes sense !
