### ISSUE TITLE
Github is toxic for you too

### ISSUE THREAD

**Issue by defly** [stravnik/toxic-repos#58]
Check out
https://github.com/Sberbank-Technology
https://github.com/sberbank-ai-lab
https://github.com/alfa-laboratory

**Comment by TodNaz** [comment]
> Check out https://github.com/Sberbank-Technology https://github.com/sberbank-ai-lab https://github.com/alfa-laboratory

These are sanctions, not github. So, github is here only as an intermediary and is not "toxic". And their blocking proves something, doesn't it?

**Comment by stravnik** [comment]
@defly And? What are you trying to say? Decryption of your message will be? Or are you one of those who just want to scream something?
