### ISSUE TITLE
pnpm.io

### ISSUE THREAD

**Issue by d0kur0** [stravnik/toxic-repos#79]
https://pnpm.io/ru/
С впна - ок, в шапке ссылка на https://war.ukraine.ua/support-ukraine/
![image](https://user-images.githubusercontent.com/31435565/171009016-9d53c760-0a5b-457a-a703-3fcc6d044a23.png)

Как же эта клоунада заебала.

**Comment by stravnik** [comment]
@d0kur0 Спасибо. Но данный ресурс уже в списке, под номером 90.
