### ISSUE TITLE
Бан и тех кто поставил звездочку

### ISSUE THREAD

**Issue by sergiomarotco** [stravnik/toxic-repos#92]
Что если при внесении проекта, автоматически вносить в бан и всех, кто поставил звезду?
Им в поле problem_type ставить причину: stargazer
Например, у [SlavaUkraini/stargazers](https://github.com/ApocalypseCalculator/SlavaUkraini/stargazers):
![image](https://user-images.githubusercontent.com/29877074/201544574-60c75117-5ee1-4df7-a499-c9bc906cc1e4.png)

**Comment by stravnik** [comment]
Не впадай в крайности.
